name: Auto test ProHire
on: push
env:
  PG_DATABASE: prohire_db_test
  PG_USER: postgres
  PG_PASSWORD: ${{ secrets.POSTGRESQL_PW }}
jobs:
  run-tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11.7
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ${{ secrets.POSTGRESQL_PW }}
          POSTGRES_DB: prohire_db_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: cd server && npm ci

      - name: Run unit tests
        id: unit-tests
        run: cd server && npm test

      - name: Run the app
        id: run-app
        run: |
          cd server
          npm install
          npx sequelize-cli db:drop
          npx sequelize-cli db:create
          npx sequelize-cli db:migrate
          PORT=3000 npm start &
          sleep 5

      - name: Run integration tests
        id: integration-tests
        run: |
          cd server
          npm install cypress cypress-json-results
          npx cypress run

      - name: Debug GitHub Run URL
        run: echo "GitHub Run URL: ${{ github.run_url }}"

      - name: Notify Slack
        if: ${{ always() }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          if [[ ${{ job.status }} == 'success' ]]; then
            curl -X POST -H 'Content-type: application/json' --data '{"text":"Workflow *Auto test ProHire* completed successfully. Check the logs for details: ${{ github.run_url }}"}' $SLACK_WEBHOOK_URL
          else
            # Fetch error details from job logs
            unit_test_result=$(echo "${{ steps.unit-tests.outputs.run-result }}")
            integration_test_result=$(echo "${{ steps.integration-tests.outputs.run-result }}")
            error_message="Unit Tests: $unit_test_result\nIntegration Tests: $integration_test_result"
            curl -X POST -H 'Content-type: application/json' --data '{"text":"Workflow *Auto test ProHire* failed. Reason:\n$error_message\nCheck the logs for details: ${{ github.run_url }}"}' $SLACK_WEBHOOK_URL
          fi
